SELECT 

parcel.PARID,
parcel.PROPERTYHOUSENUM,
parcel.PROPERTYADDRESS,
parcel.PROPERTYCITY,
parcel.PROPERTYZIP,
parcel.SALEDATE,
parcel.SALEPRICE,
parcel.FINISHEDLIVINGAREA,
parcel.SALEPRICE/parcel.FINISHEDLIVINGAREA AS PRICE_SQ_FT,
parcel.*

from pbgh_property.allegheny_cty_parcels_2021 parcel
 
 WHERE 1=1
 AND RIGHT(SALEDATE,4) IN ('2020','2021')
 AND CLASSDESC='RESIDENTIAL'
AND USEDESC = 'SINGLE FAMILY'
AND SALEPRICE >=30000 ;
 #AND LEFT(SALEDATE,2) = '07'
 #AND NEIGHDESC = 'SHADYSIDE'
#AND PROPERTYADDRESS LIKE '%ALDERSON%'

 
 